### JSF CONFIGS ###
server:
  context_parameters:
    com:
      sun:
        faces:
          forceLoadConfiguration: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/votedb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace